on: [push]
name: Sharkey.rs CI
env:
  BLAHAJ_API_TOKEN: ${{ secrets.BLAHAJ_API_TOKEN }}
jobs:
  build_and_test:
    name: Sharkey.rs CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Run tests."
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: "Test invalid CLI args."
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --features=cli
          
      - name: "Get version info."
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --features=cli \
            -- --version

      - name: "Get help info."
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --features=cli \
            -- --help

      - name: "Follow \"https://blahaj.zone/@frisaf.\"."
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --features=cli \
            -- --mflow \
            --tauth $BLAHAJ_API_TOKEN \
            --apiad "/api" \
            --inadd "https://blahaj.zone" \
            -namei "9upmnr8igmxe01k3"
            
      - name: "Unfollow \"https://blahaj.zone/@frisaf\"."
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --features=cli \
            -- --dflow \
            --tauth $BLAHAJ_API_TOKEN \
            --apiad "/api" \
            --inadd "https://blahaj.zone" \
            -namei "9upmnr8igmxe01k3"

      - name: "Make a new note on my account."
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --features=cli \
            -- --postn \
            --tauth $BLAHAJ_API_TOKEN \
            --apiad "/api" \
            --inadd "https://blahaj.zone" \
            --conte "Posted from the test for the Sharkey.rs CLI triggered by commit https://github.com/alyxshang/sharkey.rs/commit/{{ $GITHUB_SHA }}." \
            --visie "public" \
            --etype "LikeOnly" 
